#!/usr/bin/env python3
"""Genere l'index des filtres de correction de casque (HpCF) publies par AutoEQ.

AutoEQ compte plus de 50 000 fichiers : impossible de les embarquer. On indexe
donc uniquement les FIR a phase minimale en 48 kHz — notre frequence de travail,
ce qui evite tout reechantillonnage — et le WAV est telecharge a la demande.

L'arborescence est parcourue **source par source** et non d'un seul appel
recursif : sur ce depot, l'API GitHub tronque la reponse globale (elle renvoie
truncated=true) meme authentifiee, ce qui produirait un index incomplet sans
aucun signe visible. Le script echoue bruyamment si une sous-arborescence est
tronquee a son tour.

Le chemin n'est pas stocke : il se reconstruit a partir des trois champs, ce qui
divise la taille de l'index par deux.

    results/{source}/{category}/{name}/{name} minimum phase 48000Hz.wav

Usage : python3 tools/generate_hpcf_index.py > share/hpcf-index.tsv
"""
import json
import subprocess
import sys
import urllib.request

REPO = "jaakkopasanen/AutoEq"
BRANCH = "master"
SUFFIX = " minimum phase 48000Hz.wav"

_gh = None


def api(path):
    """Interroge l'API GitHub, via gh si disponible (quota bien plus large)."""
    global _gh
    if _gh is None:
        _gh = subprocess.call(["sh", "-c", "command -v gh >/dev/null"]) == 0
    if _gh:
        out = subprocess.run(["gh", "api", path], capture_output=True, text=True)
        if out.returncode == 0:
            return json.loads(out.stdout)
        print(f"  gh a echoue sur {path}, repli sur HTTP anonyme", file=sys.stderr)
    req = urllib.request.Request(
        f"https://api.github.com/{path}",
        headers={"Accept": "application/vnd.github+json"},
    )
    with urllib.request.urlopen(req, timeout=120) as r:
        return json.load(r)


def subtree(sha, label):
    d = api(f"repos/{REPO}/git/trees/{sha}?recursive=1")
    if d.get("truncated"):
        sys.exit(f"sous-arborescence « {label} » tronquee : index incomplet, abandon.")
    return d["tree"]


def main():
    root = api(f"repos/{REPO}/git/trees/{BRANCH}")
    results_dir = next((e for e in root["tree"]
                      if e["path"] == "results" and e["type"] == "tree"), None)
    if not results_dir:
        sys.exit("dossier « results » introuvable dans le depot AutoEQ.")

    sources = [e for e in api(f"repos/{REPO}/git/trees/{results_dir['sha']}")["tree"]
               if e["type"] == "tree"]
    print(f"{len(sources)} sources de mesure", file=sys.stderr)

    rows = []
    for s in sources:
        source = s["path"]
        n = 0
        for e in subtree(s["sha"], source):
            if e["type"] != "blob" or not e["path"].endswith(SUFFIX):
                continue
            parts = e["path"].split("/")   # category / name / filename
            if len(parts) != 3:
                continue
            category, name, filename = parts
            # Dossier et fichier doivent porter le meme nom, sinon le chemin
            # n'est pas reconstructible et l'entree serait inutilisable.
            if filename != name + SUFFIX:
                continue
            if "\t" in name or "\t" in source or "\t" in category:
                continue
            rows.append((name, category, source))
            n += 1
        print(f"  {source:<24} {n:>5}", file=sys.stderr)

    rows.sort(key=lambda x: (x[0].lower(), x[2].lower()))
    print("# name\tcategory\tsource — generated by tools/generate_hpcf_index.py")
    for name, category, source in rows:
        print(f"{name}\t{category}\t{source}")
    print(f"TOTAL {len(rows)} entrees", file=sys.stderr)


if __name__ == "__main__":
    main()
